SET C51INC=D:\Program Files\Keil\C51\Inc;D:\Program Files\Keil\C51\Inc\STC
SET C51LIB=D:\Program Files\Keil\C51\Lib
SET CPU_TYPE=STC15F2K60S2
SET CPU_VENDOR=STC
SET UV2_TARGET=project
SET CPU_XTAL=0x02160EC0
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\SYS_EE~1.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\SYS_DE~1.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\sys_uart.__i
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\main.__i
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\HWA_EE~1.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\HWA_EE~2.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\hwa_uart.__i
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\DRIVE_~1.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\DRIVE_~2.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\DRIVE_~3.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\DRIVE_~4.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\APP_CO~1.__I
"D:\Program Files\Keil\C51\BIN\C51.EXE" @.\app_time.__i
"D:\Program Files\Keil\C51\BIN\LX51.EXE" @PC01_01.lnp
"D:\Program Files\Keil\C51\BIN\OHX51.EXE" "PC01_01" HEX
